# .github/workflows/symfony-ci.yml
name: LogisTrack Symfony PR Check

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

defaults:
  run:
    working-directory: logistrack-symfony

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHP lint
        run: find src -type f -name "*.php" -exec php -l {} \;

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
