name: PR Checks

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --------------------------
      # Crear red Docker si no existe
      # --------------------------
      - name: Create Docker network
        run: docker network create logistrack_network || true

      # --------------------------
      # Build Angular en GH Actions
      # --------------------------
      - name: Build Angular
        run: |
          cd logistrack-angular
          npm ci
          npm run build -- --output-path=dist/logistrack-angular --configuration=production

      # --------------------------
      # Levantar contenedores de Django y Symfony para tests
      # --------------------------
      - name: Build and up Docker Compose
        run: docker compose -f docker-compose.yml up --build -d django_app symfony_app redis logistrack_mysql

      # --------------------------
      # Run Django tests con coverage
      # --------------------------
      - name: ✅ Run Django tests with coverage
        run: |
          docker compose exec -T django_app bash -c '
            apt-get update && apt-get install -y curl wget
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            dockerize -wait tcp://logistrack_mysql:3306 -timeout 60s
            pip install --upgrade pip
            pip install pytest pytest-django pytest-mock pytest-sugar pytest-cov
            export DJANGO_SETTINGS_MODULE=config.settings
            pytest --cov=apps/ --cov-branch --cov-report=xml --tb=short -q
          '

      # --------------------------
      # Upload coverage report (artifact)
      # --------------------------
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.xml

      # --------------------------
      # Upload coverage to Codecov
      # --------------------------
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
