name: Main Release

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'   # Se activará cuando se cree un tag con formato vX.Y.Z

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      # --------------------------
      # Build Angular en GH Actions
      # --------------------------
      - name: Build Angular
        run: |
          cd logistrack-angular
          npm ci
          npm run build -- --output-path=dist/logistrack-angular --configuration=production

    

      # --------------------------
      # Subir Angular y Django como release assets
      # --------------------------
      - name: Upload Angular build as release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Angular Build
          files: logistrack-angular/dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



